name: Windows Build Matrix

on:
    push:
    pull_request:
    release:
        types: [created]
    create:

jobs:
    get-extension-matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.extension-matrix.outputs.matrix }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Get The Extension Matrix
              id: extension-matrix
              uses: php/php-windows-builder/extension-matrix@v1
              with:
                php-version-list: '8.0, 8.1, 8.2, 8.3, 8.4'
                arch-list: x64
    build:
        needs: get-extension-matrix
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix: ${{fromJson(needs.get-extension-matrix.outputs.matrix)}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build The Extension
              uses: php/php-windows-builder/extension@v1
              with:
                php-version: ${{ matrix.php-version }}
                arch: ${{ matrix.arch }}
                ts: ${{ matrix.ts }}
                args: --with-xdebug
                libs: zlib
                test-opcache-mode: both

    release:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ github.event_name == 'release' }}
        steps:
            - name: Upload artifact to the release
              uses: php/php-windows-builder/release@v1
              with:
                release: ${{ github.event.release.tag_name }}
                token: ${{ secrets.GITHUB_TOKEN }}
